pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r wizard/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
    
#include:
 # - local: '.gitlab-ci-sonar.yml'
